"""add budget to users

Revision ID: e46fdd00d07b
Revises: 693e9ae45e7b
Create Date: 2026-09-01 16:25:43.571268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46fdd00d07b'
down_revision: Union[str, Sequence[str], None] = '693e9ae45e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('budget', sa.Float(), server_default='0', nullable=False))
    op.create_check_constraint("ck_user_budget_non_negative", "users", "budget >= 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'budget')
    op.drop_constraint("ck_user_budget_non_negative", "users", type_="check")
    # ### end Alembic commands ###
