// 消费类型
export const consumptionType = [
  { key: 'foods', name: '餐饮' },
  { key: 'cosmetics', name: '化妆品' },
  { key: 'daily', name: '日用品' },
  { key: 'beauty', name: '美容' },
  { key: 'jewelry', name: '首饰' },
  { key: 'wash', name: '洗鞋洗衣' },
  { key: 'redPacket', name: '红包' },
  { key: 'transportation', name: '交通费' },
  { key: 'medical', name: '医疗' },
  { key: 'clothing', name: '服装' },
  { key: 'shoes', name: '鞋子' },
  { key: 'cat', name: '猫' },
  { key: 'cashGift', name: '礼金' },
  { key: 'communication', name: '通讯' },
  { key: 'entertainment', name: '娱乐' },
  { key: 'trip', name: '路费' },
  { key: 'rent', name: '房租', tag: 'rent' },
  { key: 'insurance', name: '保险', tag: 'insurance' },
  { key: 'learn', name: '学习', tag: 'learn' },
  { key: 'parents', name: '父母', tag: 'parentsSavings' },
  { key: 'lend', name: '借出款', tag: 'lend' },
  { key: 'lend', name: '还款', tag: 'repayment' },
]