version: '2.1'

services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
  mysql:
    image: mysql
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: test
      MYSQL_ROOT_PASSWORD: test
  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080
  redis:
    image: redis
    ports: 
      - 6379:6379